#pragma once

#include "Tem.h"
struct SeinStateUpdate {
	app::AbilityType__Enum AbilityType;
	bool Active;
};

struct SeinShardUpdate {
	app::SpiritShardType__Enum ShardType;
	bool Active;
};

enum SeinRestoreState {
	IsStored = 0,
	HasBeenRestored = 1,
	IsEmpty = 3,
	IsModified = 4
};

enum InventoryItemType {
	None = 0,
	Weapon_Hammer = 1000,
	Weapon_Bow = 1001,
	Weapon_Sword = 1002,
	Weapon_Torch = 1003,
	Weapon_Swordstaff = 1004,
	Weapon_Chainsword = 1005,
	Spell_Shot = 2000,
	Spell_HomingMissiles = 2001,
	Spell_Wave = 2002,
	Spell_Whirl = 2003,
	Spell_Glow = 2004,
	Spell_LockOn = 2005,
	Spell_Shield = 2006,
	Spell_Invisibility = 2007,
	Spell_LifeAbsorb = 2008,
	Spell_Shards = 2009,
	Spell_StickyMine = 2010,
	Spell_Sentry = 2011,
	Spell_Spear = 2012,
	Spell_Meditate = 2013,
	Spell_Teleport = 2014,
	Spell_Chakram = 2015,
	Spell_Blaze = 2016,
	Spell_Turret = 2017,
	Spell_GoldenSein = 2018,
	Spell_ChargeJump = 2019,
	Ability_Bash = 3000,
	Ability_Leash = 3001,
	Ability_Digging = 3002,
	Ability_Drill = 3003,
	Ability_DoubleJump = 3004,
	Ability_FeatherFlap = 3005,
	AutoAbility_Dash = 4000,
	AutoAbility_Bounce = 4001,
	AutoAbility_Glide = 4002,
	AutoAbility_ChargeJump = 4003,
	AutoAbility_WaterDash = 4004,
	AutoAbility_Climb = 4005,
	AutoAbility_WeaponCharge = 4006,
	AutoAbility_DamageUpgradeA = 4007,
	AutoAbility_DamageUpgradeB = 4008,
	AutoAbility_WaterBreath = 4009
};

static const std::unordered_map<int, int> AbilityTypeToInventoryItemType = {
	{255, 0},
	{98,1000},
	{97 , 1001},
	{100,1002},
	{99, 1003},
	{110, 1004},
	{111, 1005},
	{78, 2000},
	{92, 2001},
	{87,2002},
	{61, 2003},
	{62, 2004},
	{63, 2005},
	{65, 2006},
	{67, 2007},
	{76, 2008},
	{79, 2009},
	{51, 2010},
	{80, 2011},
	{74, 2012},
	{77, 2013},
	{105, 2014},
	{106, 2015},
	{115, 2016},
	{116, 2017},
	{108, 2018},
	{8, 2019},
	{0, 3000},
	{57, 3001},
	{101, 3002},
	{107, 3003},
	{5, 3004},
	{118, 3005},
	{102, 4000},
	{56, 4001},
	{14, 4002},
	{8, 4003},
	{104 , 4004},
	{12, 4005},
	{119,4006},
	{120 , 4007},
	{121, 4008},
	{23 , 4009}
};

static const std::unordered_map<int, std::string> AbilityTypeToString = {
	{255, "None"},
	{0, "Bash"},
	{2, "ChargeFlame"},
	{3, "WallJump" },
	{4,"Stomp"},
	{5, "DoubleJump"},
	{8, "ChargeJump"},
	{10,"Magnet"},
	{11,"UltraMagnet"},
	{12,"Climb"},
	{14,"Glide"},
	{15,"SpiritFlame"},
	{17,"RapidFlame"},
	{18,"SplitFlameUpgrade"},
	{22,"SoulEfficiency"},
	{23,"WaterBreath"},
	{27,"ChargeFlameBlast"},
	{28,"ChargeFlameBurn"},
	{29,"DoubleJumpUpgrade"},
	{30,"BashBuff"},
	{31,"UltraDefense"},
	{32,"HealthEfficiency"},
	{33,"Sense"},
	{34,"UltraStomp"},
	{36,"SparkFlame"},
	{37,"QuickFlame"},
	{38,"MapMarkers"},
	{39,"EnergyEfficiency"},
	{40,"HealthMarkers"},
	{41,"EnergyMarkers"},
	{42,"AbilityMarkers"},
	{43,"Rekindle"},
	{44,"Regroup"},
	{45,"ChargeFlameEfficiency"},
	{46,"UltraSoulFlame"},
	{47,"SoulFlameEfficiency"},
	{48,"CinderFlame"},
	{49,"UltraSplitFlame"},
	{50,"Dash"},
	{51,"Grenade"},
	{52,"GrenadeUpgrade"},
	{53,"ChargeDash"},
	{54,"AirDash"},
	{55,"GrenadeEfficiency"},
	{56,"Bounce"},
	{57,"SpiritLeash"},
	{58,"SpiritSlash"},
	{59,"HeavySpiritSlash"},
	{60,"FireburstSpell"},
	{61,"FirewhirlSpell"},
	{62,"GlowSpell"},
	{63,"LockOnSpell"},
	{64,"TimeWarpSpell"},
	{65,"ShieldSpell"},
	{66,"EnergyWallSpell"},
	{67,"InvisibilitySpell"},
	{68,"TrapSpell"},
	{69,"WarpSpell"},
	{70,"LightSpell"},
	{71,"MindControlSpell"},
	{72,"MirageSpell"},
	{73,"StickyMineSpell"},
	{74,"SpiritSpearSpell"},
	{75,"LightSpearSpell"},
	{76,"LifeAbsorbSpell"},
	{77,"MeditateSpell"},
	{78,"ChargeShotSpell"},
	{79,"SpiritShardsSpell"},
	{80,"SpiritSentrySpell"},
	{81,"PowerslideSpell"},
	{82,"CounterstrikeSpell"},
	{83,"EarthShatterSpell"},
	{84,"JumpShotSpell"},
	{85,"RoundupLeashSpell"},
	{86,"BurrowSpell"},
	{87,"PowerOfFriendshipSpell"},
	{88,"LightningSpell"},
	{89,"SpiritFlareSpell"},
	{90,"EntanglingRootsSpell"},
	{91,"MarkOfTheWildsSpell"},
	{92,"HomingMissileSpell"},
	{93,"SpiritCrescentSpell"},
	{94,"MineSpell"},
	{95,"Pinned"},
	{96,"Leached"},
	{97,"Bow"},
	{98,"Hammer"},
	{99,"Torch"},
	{100,"Sword"},
	{101,"Digging"},
	{102,"DashNew"},
	{103,"Launch"},
	{104,"WaterDash"},
	{105,"TeleportSpell"},
	{106,"ChakramSpell"},
	{107,"Drill"},
	{108,"GoldenSein"},
	{109,"BowCharge"},
	{110,"Swordstaff"},
	{111,"Chainsword"},
	{112,"SpiritMagnet"},
	{113,"SwordCharge"},
	{114,"HammerCharge"},
	{115,"Blaze"},
	{116,"TurretSpell"},
	{117,"Regenerate"},
	{118,"FeatherFlap"},
	{119,"WeaponCharge"},
	{120,"DamageUpgradeA"},
	{121,"DamageUpgradeB"},
	{256,"BlazeUpgrade" },
	{257,"ChakramUpgrade" },
	{258,"Shockwave" },
	{259,"SpiritSentryUpgrade" },
	{260,"SpiritSpearUpgrade" }
};

static const std::unordered_map<int, int> AbilityUpgradeToByte = {
	{256,61898},
	{257,10776},
	{258,46488},
	{259,57376 },
	{260,24142 }
};

static const std::unordered_map< app::AbilityType__Enum, app::EquipmentType__Enum> AbilityTypeToEquipmentType = {
#ifdef _WOTW_PATCH_THREE
	{app::AbilityType__Enum::AbilityType__Enum_None, app::EquipmentType__Enum::EquipmentType__Enum_None},
	{app::AbilityType__Enum::AbilityType__Enum_Bash, app::EquipmentType__Enum::EquipmentType__Enum_Ability_Bash},
	{app::AbilityType__Enum::AbilityType__Enum_Digging, app::EquipmentType__Enum::EquipmentType__Enum_Ability_Digging},
	{app::AbilityType__Enum::AbilityType__Enum_DoubleJump, app::EquipmentType__Enum::EquipmentType__Enum_Ability_DoubleJump},
	{app::AbilityType__Enum::AbilityType__Enum_Drill, app::EquipmentType__Enum::EquipmentType__Enum_Ability_Drill},
	{app::AbilityType__Enum::AbilityType__Enum_FeatherFlap, app::EquipmentType__Enum::EquipmentType__Enum_Ability_FeatherFlap},
	{app::AbilityType__Enum::AbilityType__Enum_SpiritLeash, app::EquipmentType__Enum::EquipmentType__Enum_Ability_Leash},
	{app::AbilityType__Enum::AbilityType__Enum_Bounce, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_Bounce},
	//{app::AbilityType__Enum::AbilityType__Enum_ChargeJump, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_ChargeJump},
	{app::AbilityType__Enum::AbilityType__Enum_Climb, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_Climb},
	{app::AbilityType__Enum::AbilityType__Enum_DamageUpgradeA, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_DamageUpgradeA},
	{app::AbilityType__Enum::AbilityType__Enum_DamageUpgradeB, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_DamageUpgradeB},
	{app::AbilityType__Enum::AbilityType__Enum_Dash, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_Dash},
	{app::AbilityType__Enum::AbilityType__Enum_Glide, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_Glide},
	{app::AbilityType__Enum::AbilityType__Enum_WaterBreath, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_WaterBreath},
	{app::AbilityType__Enum::AbilityType__Enum_WaterDash, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_WaterDash},
	{app::AbilityType__Enum::AbilityType__Enum_WeaponCharge, app::EquipmentType__Enum::EquipmentType__Enum_AutoAbility_WeaponCharge},
	{app::AbilityType__Enum::AbilityType__Enum_Blaze, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Blaze},
	{app::AbilityType__Enum::AbilityType__Enum_ChakramSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Chakram},
	{app::AbilityType__Enum::AbilityType__Enum_ChargeJump, app::EquipmentType__Enum::EquipmentType__Enum_Spell_ChargeJump},
	{app::AbilityType__Enum::AbilityType__Enum_GlowSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Glow},
	{app::AbilityType__Enum::AbilityType__Enum_GoldenSein, app::EquipmentType__Enum::EquipmentType__Enum_Spell_GoldenSein},
	{app::AbilityType__Enum::AbilityType__Enum_HomingMissileSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_HomingMissiles},
	{app::AbilityType__Enum::AbilityType__Enum_InvisibilitySpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Invisibility},
	{app::AbilityType__Enum::AbilityType__Enum_LifeAbsorbSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_LifeAbsorb},
	{app::AbilityType__Enum::AbilityType__Enum_LockOnSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_LockOn},
	{app::AbilityType__Enum::AbilityType__Enum_MeditateSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Meditate},
	{app::AbilityType__Enum::AbilityType__Enum_SpiritSentrySpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Sentry},
	{app::AbilityType__Enum::AbilityType__Enum_SpiritShardsSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Shards},
	{app::AbilityType__Enum::AbilityType__Enum_ShieldSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Shield},
	{app::AbilityType__Enum::AbilityType__Enum_ChargeShotSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Shot},
	{app::AbilityType__Enum::AbilityType__Enum_SpiritSpearSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Spear},
	{app::AbilityType__Enum::AbilityType__Enum_StickyMineSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_StickyMine},
	{app::AbilityType__Enum::AbilityType__Enum_TeleportSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Teleport},
	{app::AbilityType__Enum::AbilityType__Enum_TurretSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Turret},
	{app::AbilityType__Enum::AbilityType__Enum_WarpSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Wave},
	{app::AbilityType__Enum::AbilityType__Enum_FirewhirlSpell, app::EquipmentType__Enum::EquipmentType__Enum_Spell_Whirl},
	{app::AbilityType__Enum::AbilityType__Enum_Bow, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Bow},
	{app::AbilityType__Enum::AbilityType__Enum_Chainsword, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Chainsword},
	{app::AbilityType__Enum::AbilityType__Enum_Hammer, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Hammer},
	{app::AbilityType__Enum::AbilityType__Enum_Sword, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Sword},
	{app::AbilityType__Enum::AbilityType__Enum_Swordstaff, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Swordstaff},
	{app::AbilityType__Enum::AbilityType__Enum_Torch, app::EquipmentType__Enum::EquipmentType__Enum_Weapon_Torch}
#endif
#ifdef _WOTW_PATCH_TWO
	{app::AbilityType__Enum::None, app::EquipmentType__Enum::None},
	{app::AbilityType__Enum::Bash, app::EquipmentType__Enum::Ability_Bash},
	{app::AbilityType__Enum::Digging, app::EquipmentType__Enum::Ability_Digging},
	{app::AbilityType__Enum::DoubleJump, app::EquipmentType__Enum::Ability_DoubleJump},
	{app::AbilityType__Enum::Drill, app::EquipmentType__Enum::Ability_Drill},
	{app::AbilityType__Enum::FeatherFlap, app::EquipmentType__Enum::Ability_FeatherFlap},
	{app::AbilityType__Enum::SpiritLeash, app::EquipmentType__Enum::Ability_Leash},
	{app::AbilityType__Enum::Bounce, app::EquipmentType__Enum::AutoAbility_Bounce},
	//{app::AbilityType__Enum::ChargeJump, app::EquipmentType__Enum::AutoAbility_ChargeJump},
	{app::AbilityType__Enum::Climb, app::EquipmentType__Enum::AutoAbility_Climb},
	{app::AbilityType__Enum::DamageUpgradeA, app::EquipmentType__Enum::AutoAbility_DamageUpgradeA},
	{app::AbilityType__Enum::DamageUpgradeB, app::EquipmentType__Enum::AutoAbility_DamageUpgradeB},
	{app::AbilityType__Enum::Dash, app::EquipmentType__Enum::AutoAbility_Dash},
	{app::AbilityType__Enum::Glide, app::EquipmentType__Enum::AutoAbility_Glide},
	{app::AbilityType__Enum::WaterBreath, app::EquipmentType__Enum::AutoAbility_WaterBreath},
	{app::AbilityType__Enum::WaterDash, app::EquipmentType__Enum::AutoAbility_WaterDash},
	{app::AbilityType__Enum::WeaponCharge, app::EquipmentType__Enum::AutoAbility_WeaponCharge},
	{app::AbilityType__Enum::Blaze, app::EquipmentType__Enum::Spell_Blaze},
	{app::AbilityType__Enum::ChakramSpell, app::EquipmentType__Enum::Spell_Chakram},
	{app::AbilityType__Enum::ChargeJump, app::EquipmentType__Enum::Spell_ChargeJump},
	{app::AbilityType__Enum::GlowSpell, app::EquipmentType__Enum::Spell_Glow},
	{app::AbilityType__Enum::GoldenSein, app::EquipmentType__Enum::Spell_GoldenSein},
	{app::AbilityType__Enum::HomingMissileSpell, app::EquipmentType__Enum::Spell_HomingMissiles},
	{app::AbilityType__Enum::InvisibilitySpell, app::EquipmentType__Enum::Spell_Invisibility},
	{app::AbilityType__Enum::LifeAbsorbSpell, app::EquipmentType__Enum::Spell_LifeAbsorb},
	{app::AbilityType__Enum::LockOnSpell, app::EquipmentType__Enum::Spell_LockOn},
	{app::AbilityType__Enum::MeditateSpell, app::EquipmentType__Enum::Spell_Meditate},
	{app::AbilityType__Enum::SpiritSentrySpell, app::EquipmentType__Enum::Spell_Sentry},
	{app::AbilityType__Enum::SpiritShardsSpell, app::EquipmentType__Enum::Spell_Shards},
	{app::AbilityType__Enum::ShieldSpell, app::EquipmentType__Enum::Spell_Shield},
	{app::AbilityType__Enum::ChargeShotSpell, app::EquipmentType__Enum::Spell_Shot},
	{app::AbilityType__Enum::SpiritSpearSpell, app::EquipmentType__Enum::Spell_Spear},
	{app::AbilityType__Enum::StickyMineSpell, app::EquipmentType__Enum::Spell_StickyMine},
	{app::AbilityType__Enum::TeleportSpell, app::EquipmentType__Enum::Spell_Teleport},
	{app::AbilityType__Enum::TurretSpell, app::EquipmentType__Enum::Spell_Turret},
	{app::AbilityType__Enum::WarpSpell, app::EquipmentType__Enum::Spell_Wave},
	{app::AbilityType__Enum::FirewhirlSpell, app::EquipmentType__Enum::Spell_Whirl},
	{app::AbilityType__Enum::Bow, app::EquipmentType__Enum::Weapon_Bow},
	{app::AbilityType__Enum::Chainsword, app::EquipmentType__Enum::Weapon_Chainsword},
	{app::AbilityType__Enum::Hammer, app::EquipmentType__Enum::Weapon_Hammer},
	{app::AbilityType__Enum::Sword, app::EquipmentType__Enum::Weapon_Sword},
	{app::AbilityType__Enum::Swordstaff, app::EquipmentType__Enum::Weapon_Swordstaff},
	{app::AbilityType__Enum::Torch, app::EquipmentType__Enum::Weapon_Torch}
#endif
};

static const std::vector< app::AbilityType__Enum> AbilityTypeList = std::vector< app::AbilityType__Enum>() = {
#ifdef _WOTW_PATCH_THREE
	app::AbilityType__Enum::AbilityType__Enum_AbilityMarkers,
	app::AbilityType__Enum::AbilityType__Enum_AirDash,
	app::AbilityType__Enum::AbilityType__Enum_Bash,
	app::AbilityType__Enum::AbilityType__Enum_BashBuff,
	app::AbilityType__Enum::AbilityType__Enum_Blaze,
	app::AbilityType__Enum::AbilityType__Enum_Bounce,
	app::AbilityType__Enum::AbilityType__Enum_Bow,
	app::AbilityType__Enum::AbilityType__Enum_BowCharge,
	app::AbilityType__Enum::AbilityType__Enum_BurrowSpell,
	app::AbilityType__Enum::AbilityType__Enum_BurrowSpell,
	app::AbilityType__Enum::AbilityType__Enum_Chainsword,
	app::AbilityType__Enum::AbilityType__Enum_ChakramSpell,
	app::AbilityType__Enum::AbilityType__Enum_ChargeDash,
	app::AbilityType__Enum::AbilityType__Enum_ChargeFlame,
	app::AbilityType__Enum::AbilityType__Enum_ChargeFlameBlast,
	app::AbilityType__Enum::AbilityType__Enum_ChargeFlameBurn,
	app::AbilityType__Enum::AbilityType__Enum_ChargeFlameEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_ChargeJump,
	app::AbilityType__Enum::AbilityType__Enum_ChargeShotSpell,
	app::AbilityType__Enum::AbilityType__Enum_CinderFlame,
	app::AbilityType__Enum::AbilityType__Enum_Climb,
	app::AbilityType__Enum::AbilityType__Enum_CounterstrikeSpell,
	app::AbilityType__Enum::AbilityType__Enum_DamageUpgradeA,
	app::AbilityType__Enum::AbilityType__Enum_DamageUpgradeB,
	app::AbilityType__Enum::AbilityType__Enum_Dash,
	app::AbilityType__Enum::AbilityType__Enum_DashNew,
	app::AbilityType__Enum::AbilityType__Enum_Digging,
	app::AbilityType__Enum::AbilityType__Enum_DoubleJump,
	app::AbilityType__Enum::AbilityType__Enum_DoubleJumpUpgrade,
	app::AbilityType__Enum::AbilityType__Enum_Drill,
	app::AbilityType__Enum::AbilityType__Enum_EarthShatterSpell,
	app::AbilityType__Enum::AbilityType__Enum_EnergyEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_EnergyMarkers,
	app::AbilityType__Enum::AbilityType__Enum_EnergyWallSpell,
	app::AbilityType__Enum::AbilityType__Enum_EntanglingRootsSpell,
	app::AbilityType__Enum::AbilityType__Enum_FeatherFlap,
	app::AbilityType__Enum::AbilityType__Enum_FireburstSpell,
	app::AbilityType__Enum::AbilityType__Enum_FirewhirlSpell,
	app::AbilityType__Enum::AbilityType__Enum_Glide,
	app::AbilityType__Enum::AbilityType__Enum_GlowSpell,
	app::AbilityType__Enum::AbilityType__Enum_GoldenSein,
	app::AbilityType__Enum::AbilityType__Enum_Grenade,
	app::AbilityType__Enum::AbilityType__Enum_GrenadeEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_GrenadeUpgrade,
	app::AbilityType__Enum::AbilityType__Enum_Hammer,
	app::AbilityType__Enum::AbilityType__Enum_HammerCharge,
	app::AbilityType__Enum::AbilityType__Enum_HealthEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_HealthMarkers,
	app::AbilityType__Enum::AbilityType__Enum_HeavySpiritSlash,
	app::AbilityType__Enum::AbilityType__Enum_HomingMissileSpell,
	app::AbilityType__Enum::AbilityType__Enum_InvisibilitySpell,
	app::AbilityType__Enum::AbilityType__Enum_JumpShotSpell,
	app::AbilityType__Enum::AbilityType__Enum_Launch,
	app::AbilityType__Enum::AbilityType__Enum_Leached,
	app::AbilityType__Enum::AbilityType__Enum_LifeAbsorbSpell,
	app::AbilityType__Enum::AbilityType__Enum_LightningSpell,
	app::AbilityType__Enum::AbilityType__Enum_LightSpearSpell,
	app::AbilityType__Enum::AbilityType__Enum_LightSpell,
	app::AbilityType__Enum::AbilityType__Enum_LockOnSpell,
	app::AbilityType__Enum::AbilityType__Enum_Magnet,
	app::AbilityType__Enum::AbilityType__Enum_MapMarkers,
	app::AbilityType__Enum::AbilityType__Enum_MarkOfTheWildsSpell,
	app::AbilityType__Enum::AbilityType__Enum_MeditateSpell,
	app::AbilityType__Enum::AbilityType__Enum_MindControlSpell,
	app::AbilityType__Enum::AbilityType__Enum_MineSpell,
	app::AbilityType__Enum::AbilityType__Enum_MirageSpell,
	app::AbilityType__Enum::AbilityType__Enum_None,
	app::AbilityType__Enum::AbilityType__Enum_Pinned,
	app::AbilityType__Enum::AbilityType__Enum_PowerOfFriendshipSpell,
	app::AbilityType__Enum::AbilityType__Enum_PowerslideSpell,
	app::AbilityType__Enum::AbilityType__Enum_QuickFlame,
	app::AbilityType__Enum::AbilityType__Enum_RapidFlame,
	app::AbilityType__Enum::AbilityType__Enum_Regenerate,
	app::AbilityType__Enum::AbilityType__Enum_Regroup,
	app::AbilityType__Enum::AbilityType__Enum_Rekindle,
	app::AbilityType__Enum::AbilityType__Enum_RoundupLeashSpell,
	app::AbilityType__Enum::AbilityType__Enum_Sense,
	app::AbilityType__Enum::AbilityType__Enum_ShieldSpell,
	app::AbilityType__Enum::AbilityType__Enum_SoulEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_SoulFlameEfficiency,
	app::AbilityType__Enum::AbilityType__Enum_SparkFlame,
	app::AbilityType__Enum::AbilityType__Enum_SpiritCrescentSpell,
	app::AbilityType__Enum::AbilityType__Enum_SpiritFlame,
	app::AbilityType__Enum::AbilityType__Enum_SpiritFlareSpell,
	app::AbilityType__Enum::AbilityType__Enum_SpiritLeash,
	app::AbilityType__Enum::AbilityType__Enum_SpiritMagnet,
	app::AbilityType__Enum::AbilityType__Enum_SpiritSentrySpell,
	app::AbilityType__Enum::AbilityType__Enum_SpiritShardsSpell,
	app::AbilityType__Enum::AbilityType__Enum_SpiritSlash,
	app::AbilityType__Enum::AbilityType__Enum_SpiritSpearSpell,
	app::AbilityType__Enum::AbilityType__Enum_SplitFlameUpgrade,
	app::AbilityType__Enum::AbilityType__Enum_StickyMineSpell,
	app::AbilityType__Enum::AbilityType__Enum_Stomp,
	app::AbilityType__Enum::AbilityType__Enum_Sword,
	app::AbilityType__Enum::AbilityType__Enum_SwordCharge,
	app::AbilityType__Enum::AbilityType__Enum_Swordstaff,
	app::AbilityType__Enum::AbilityType__Enum_TeleportSpell,
	app::AbilityType__Enum::AbilityType__Enum_TimeWarpSpell,
	app::AbilityType__Enum::AbilityType__Enum_Torch,
	app::AbilityType__Enum::AbilityType__Enum_TrapSpell,
	app::AbilityType__Enum::AbilityType__Enum_TurretSpell,
	app::AbilityType__Enum::AbilityType__Enum_UltraDefense,
	app::AbilityType__Enum::AbilityType__Enum_UltraMagnet,
	app::AbilityType__Enum::AbilityType__Enum_UltraSoulFlame,
	app::AbilityType__Enum::AbilityType__Enum_UltraSplitFlame,
	app::AbilityType__Enum::AbilityType__Enum_UltraStomp,
	app::AbilityType__Enum::AbilityType__Enum_WallJump,
	app::AbilityType__Enum::AbilityType__Enum_WarpSpell,
	app::AbilityType__Enum::AbilityType__Enum_WaterBreath,
	app::AbilityType__Enum::AbilityType__Enum_WaterDash,
	app::AbilityType__Enum::AbilityType__Enum_WeaponCharge
#endif
#ifdef _WOTW_PATCH_TWO
		app::AbilityType__Enum::AbilityMarkers,
		app::AbilityType__Enum::AirDash,
		app::AbilityType__Enum::Bash,
		app::AbilityType__Enum::BashBuff,
		app::AbilityType__Enum::Blaze,
		app::AbilityType__Enum::Bounce,
		app::AbilityType__Enum::Bow,
		app::AbilityType__Enum::BowCharge,
		app::AbilityType__Enum::BurrowSpell,
		app::AbilityType__Enum::BurrowSpell,
		app::AbilityType__Enum::Chainsword,
		app::AbilityType__Enum::ChakramSpell,
		app::AbilityType__Enum::ChargeDash,
		app::AbilityType__Enum::ChargeFlame,
		app::AbilityType__Enum::ChargeFlameBlast,
		app::AbilityType__Enum::ChargeFlameBurn,
		app::AbilityType__Enum::ChargeFlameEfficiency,
		app::AbilityType__Enum::ChargeJump,
		app::AbilityType__Enum::ChargeShotSpell,
		app::AbilityType__Enum::CinderFlame,
		app::AbilityType__Enum::Climb,
		app::AbilityType__Enum::CounterstrikeSpell,
		app::AbilityType__Enum::DamageUpgradeA,
		app::AbilityType__Enum::DamageUpgradeB,
		app::AbilityType__Enum::Dash,
		app::AbilityType__Enum::DashNew,
		app::AbilityType__Enum::Digging,
		app::AbilityType__Enum::DoubleJump,
		app::AbilityType__Enum::DoubleJumpUpgrade,
		app::AbilityType__Enum::Drill,
		app::AbilityType__Enum::EarthShatterSpell,
		app::AbilityType__Enum::EnergyEfficiency,
		app::AbilityType__Enum::EnergyMarkers,
		app::AbilityType__Enum::EnergyWallSpell,
		app::AbilityType__Enum::EntanglingRootsSpell,
		app::AbilityType__Enum::FeatherFlap,
		app::AbilityType__Enum::FireburstSpell,
		app::AbilityType__Enum::FirewhirlSpell,
		app::AbilityType__Enum::Glide,
		app::AbilityType__Enum::GlowSpell,
		app::AbilityType__Enum::GoldenSein,
		app::AbilityType__Enum::Grenade,
		app::AbilityType__Enum::GrenadeEfficiency,
		app::AbilityType__Enum::GrenadeUpgrade,
		app::AbilityType__Enum::Hammer,
		app::AbilityType__Enum::HammerCharge,
		app::AbilityType__Enum::HealthEfficiency,
		app::AbilityType__Enum::HealthMarkers,
		app::AbilityType__Enum::HeavySpiritSlash,
		app::AbilityType__Enum::HomingMissileSpell,
		app::AbilityType__Enum::InvisibilitySpell,
		app::AbilityType__Enum::JumpShotSpell,
		app::AbilityType__Enum::Launch,
		app::AbilityType__Enum::Leached,
		app::AbilityType__Enum::LifeAbsorbSpell,
		app::AbilityType__Enum::LightningSpell,
		app::AbilityType__Enum::LightSpearSpell,
		app::AbilityType__Enum::LightSpell,
		app::AbilityType__Enum::LockOnSpell,
		app::AbilityType__Enum::Magnet,
		app::AbilityType__Enum::MapMarkers,
		app::AbilityType__Enum::MarkOfTheWildsSpell,
		app::AbilityType__Enum::MeditateSpell,
		app::AbilityType__Enum::MindControlSpell,
		app::AbilityType__Enum::MineSpell,
		app::AbilityType__Enum::MirageSpell,
		app::AbilityType__Enum::None,
		app::AbilityType__Enum::Pinned,
		app::AbilityType__Enum::PowerOfFriendshipSpell,
		app::AbilityType__Enum::PowerslideSpell,
		app::AbilityType__Enum::QuickFlame,
		app::AbilityType__Enum::RapidFlame,
		app::AbilityType__Enum::Regenerate,
		app::AbilityType__Enum::Regroup,
		app::AbilityType__Enum::Rekindle,
		app::AbilityType__Enum::RoundupLeashSpell,
		app::AbilityType__Enum::Sense,
		app::AbilityType__Enum::ShieldSpell,
		app::AbilityType__Enum::SoulEfficiency,
		app::AbilityType__Enum::SoulFlameEfficiency,
		app::AbilityType__Enum::SparkFlame,
		app::AbilityType__Enum::SpiritCrescentSpell,
		app::AbilityType__Enum::SpiritFlame,
		app::AbilityType__Enum::SpiritFlareSpell,
		app::AbilityType__Enum::SpiritLeash,
		app::AbilityType__Enum::SpiritMagnet,
		app::AbilityType__Enum::SpiritSentrySpell,
		app::AbilityType__Enum::SpiritShardsSpell,
		app::AbilityType__Enum::SpiritSlash,
		app::AbilityType__Enum::SpiritSpearSpell,
		app::AbilityType__Enum::SplitFlameUpgrade,
		app::AbilityType__Enum::StickyMineSpell,
		app::AbilityType__Enum::Stomp,
		app::AbilityType__Enum::Sword,
		app::AbilityType__Enum::SwordCharge,
		app::AbilityType__Enum::Swordstaff,
		app::AbilityType__Enum::TeleportSpell,
		app::AbilityType__Enum::TimeWarpSpell,
		app::AbilityType__Enum::Torch,
		app::AbilityType__Enum::TrapSpell,
		app::AbilityType__Enum::TurretSpell,
		app::AbilityType__Enum::UltraDefense,
		app::AbilityType__Enum::UltraMagnet,
		app::AbilityType__Enum::UltraSoulFlame,
		app::AbilityType__Enum::UltraSplitFlame,
		app::AbilityType__Enum::UltraStomp,
		app::AbilityType__Enum::WallJump,
		app::AbilityType__Enum::WarpSpell,
		app::AbilityType__Enum::WaterBreath,
		app::AbilityType__Enum::WaterDash,
		app::AbilityType__Enum::WeaponCharge
#endif
};

class SeinShard {
public:
	bool Active = false;
	int Level = 0;
	int MaxLevel = 0;
#ifdef _WOTW_PATCH_THREE
	app::SpiritShardType__Enum ShardType = app::SpiritShardType__Enum::SpiritShardType__Enum_None;
#endif
#ifdef _WOTW_PATCH_TWO
	app::SpiritShardType__Enum ShardType = app::SpiritShardType__Enum::None;
#endif
};

class SeinCharacterHelper
{
public:
	static std::vector<SeinStateUpdate> SeinAbilitiesUpgrades;
	static std::vector<SeinStateUpdate> SeinAbilitiesStates;
	static SeinRestoreState CurrentState;
	static SeinRestoreState CurrentBoundAbilitiesState;
	static SeinRestoreState CurrentShardState;
	static SeinRestoreState CurrentEquippedShardState;
	static app::AbilityType__Enum BoundAbility1;
	static app::AbilityType__Enum BoundAbility2;
	static app::AbilityType__Enum BoundAbility3;
	static std::vector<app::PlayerUberStateShards_Shard> SeinShards;
	static std::vector<app::SpiritShardType__Enum> SeinEquippedShards;

	static app::AbilityType__Enum StringToAbilityType(std::string ability);
	static void UpdateSeinStates(std::unordered_map<int, SeinStateUpdate> newStates);
	static void SetSeinState(SeinStateUpdate newState);
	static void StoreSeinAbilities();
	static void RestoreSeinAbilities();
	static void UpdateSeinAbilitiesUpgradesStates(std::unordered_map<int, SeinStateUpdate> newStates);
	static void StoreSeinAbilitiesUpgrades();
	static void RestoreSeinAbilitiesUpgrades();
	static void StoreBoundAbilities();
	static void SetBoundAbility(int index, std::string ability);
	static void RestoreBoundAbilities();
	static void StoreShards();
	static void GiveShards(std::unordered_map<int, SeinShard> shards);
	static void RestoreShards();
	static void StoreEquippedShards();
	static void EquippShards(std::vector<app::SpiritShardType__Enum> shards);
	static void RestoreEquippedShards();
	static void ClearData();
};